[build]
  publish = "build"  # ビルド後の出力先ディレクトリ（build フォルダ）
  command = "CI= npm run build"  # ビルドを行うコマンド

[context.production.environment]
  NODE_VERSION = "18"  # Node.js のバージョン
  NPM_VERSION = "10.8.2"  # npm のバージョン

[build.environment]
  NODE_OPTIONS = "--openssl-legacy-provider"